name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: docker build -t ghcr.io/hyp3rflow/${{ secrets.IMAGE_NAME }}:latest .
      - name: Push
        run: docker push ghcr.io/hyp3rflow/${{ secrets.IMAGE_NAME }}:latest
