name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t ghcr.io/hyp3rflow/${{ secrets.IMAGE }}:latest .
      - name: Push
        run: docker push ghcr.io/hyp3rflow/${{ secrets.IMAGE }}:latest
